# A number guessing game where user have to guess the number generated by computer.

import random

LOW, HIGH = 1, 10

def get_guess():
    while True:
        try:
            guess = int(input(f'Guess a number between {LOW} and {HIGH}: '))
            if LOW <= guess <= HIGH:
                return guess
            print(f'Please enter a number between {low} to {high} : ')
        except ValueError:
            print('Invalid input. Please enter a whole number.')

def ask_play_again():
    while True:
        choice = input('Do you want to play again? (yes/no): ').strip().lower()
        if choice in ('yes', 'no'):
            return choice == 'yes'
        print('Please type yes or no.')

def play_game():
    computer_num = random.randint(LOW, HIGH)
    while True:
        guess = get_guess()

        if guess < computer_num:
            print('Too Low.')
        elif guess > computer_num:
            print('Too High.')
        else:
            print("You guessed perfectly.")
            if ask_play_again():
                computer_num = random.randint(LOW, HIGH)
                print('New Game started')
            else:
                print('Good Bye')
                break

play_game()